#! /bin/sh
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
picom --config ~/.config/picom.conf &
albert &
~/.fehbg &
(cd ~/.config/eww/ && ~/.config/eww/./launch_bar) &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config border_width 6
bspc config normal_border_color "#dcc9c5" 
bspc config active_border_color "#dfb0b0"  
bspc config focused_border_color "#ecc2e4" 
bspc config presel_feedback_color "#ecc2e4" 



# rules

bspc rule -a albert border=off
bspc rule -a discord desktop=^2

